// packages/svelte/src/fixtures/test-singleton-call-store.svelte
<script lang="ts">
  import type { SingletonCallStore } from '../call-store';

  interface Props {
    store: SingletonCallStore;
  }

  const { store }: Props = $props();
</script>

{#if store.current}
  <div data-testid="current">{store.current.payload}</div>
  <button data-testid="resolve" onclick={() => store.resolve(true)}>OK</button>
  <button data-testid="reject" onclick={() => store.reject('error')}>Cancel</button>
{:else}
  <div data-testid="current">null</div>
{/if}

// packages/vue/src/fixtures/test-singleton-call-store.vue
<script setup lang="ts">
import { SingletonCallStore } from '@ui-call/core';
import { useSingletonCallStore } from '../use-store';

const props = defineProps<{
  store: SingletonCallStore;
}>();

const current = useSingletonCallStore(props.store);
</script>

<template>
  <div data-testid="current">{{ current ? current.payload : 'null' }}</div>
</template>
