// apps/svelte-demo/src/lib/components/ui/confirmer/confirmer.svelte
<script lang="ts" module>
  import * as AlertDialog from '$lib/components/ui/alert-dialog/index.js';

  import { SingletonCallStore } from '@ui-call/svelte';

  const confirmStore = new SingletonCallStore<{
    title: string;
    message: string;
  }>({
    unmountingDelay: 150,
  });

  export const confirm = confirmStore.call.bind(confirmStore);
</script>

{#if confirmStore.current}
  <AlertDialog.Root open={confirmStore.current.pending}>
    <AlertDialog.Content>
      <AlertDialog.Header>
        <AlertDialog.Title>{confirmStore.current.payload.title}</AlertDialog.Title>
        <AlertDialog.Description>
          {confirmStore.current.payload.message}
        </AlertDialog.Description>
      </AlertDialog.Header>
      <AlertDialog.Footer>
        <AlertDialog.Cancel onclick={() => confirmStore.resolve(false)}>Cancel</AlertDialog.Cancel>
        <AlertDialog.Action onclick={() => confirmStore.resolve(true)}>Continue</AlertDialog.Action>
      </AlertDialog.Footer>
    </AlertDialog.Content>
  </AlertDialog.Root>
{/if}

// apps/vue-demo/app/components/ui/confirmer/Confirmer.vue
<script setup lang="ts">
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"

import { useSingletonCallStore } from '@ui-call/vue';

const call = useSingletonCallStore(confirmStore);
</script>

<script lang="ts">
import { createSingletonCallStore } from '@ui-call/vue';

const confirmStore = createSingletonCallStore<{
  title: string;
  message: string;
}>({
  unmountingDelay: 200,
});

export const confirm = confirmStore.call.bind(confirmStore);
</script>

<template>
  <AlertDialog v-if="call" :open="call.pending">
    <AlertDialogContent>
      <AlertDialogHeader>
        <AlertDialogTitle>{{ call.payload.title }}</AlertDialogTitle>
        <AlertDialogDescription>
          {{ call.payload.message }}
        </AlertDialogDescription>
      </AlertDialogHeader>
      <AlertDialogFooter>
        <AlertDialogCancel @click="call.resolve(false)">Cancel</AlertDialogCancel>
        <AlertDialogAction @click="call.resolve(true)">Continue</AlertDialogAction>
      </AlertDialogFooter>
    </AlertDialogContent>
  </AlertDialog>
</template>
