// examples/vue-nuxt-demo/app/app.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Confirmer, confirm } from '@/components/ui/confirmer';
import { Toast, toast } from '@/components/ui/toast';
import { ModeToggle } from '@/components/mode-toggle';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';

function onUndo() {
  alert('Action clicked!');
}

function onDelete() {
  confirm({
    title: 'Are you absolutely sure?',
    message:
      'This action cannot be undone. This will permanently delete your account and remove your data from our servers.',
  }).then((result) => alert(`User ${result ? 'confirmed' : 'cancelled'} the action`));
}
</script>

<template>
  <div class="mx-auto grid w-full max-w-4xl gap-8 p-6 min-h-screen">
    <Toast />

    <section>
      <div class="flex items-start justify-between gap-4">
        <div class="space-y-2">
          <h1 class="text-2xl font-bold tracking-tight">@ui-call/vue Demo</h1>
          <p class="text-muted-foreground">Small examples showing how <code>@ui-call/vue</code> powers UI patterns.</p>
        </div>
        <ModeToggle />
      </div>
    </section>

    <div class="flex flex-col gap-8 flex-1">
      <Card>
        <CardHeader>
          <CardTitle>Confirmer</CardTitle>
          <CardDescription>
            Imperative confirm dialog built with <code>SingletonCallStore</code>.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Confirmer />
          <Button variant="destructive" @click="onDelete">Delete</Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Toast</CardTitle>
          <CardDescription>
            Sonner-like API implemented with <code>CallStore</code>.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div class="flex flex-wrap gap-2">
            <Button
              @click="toast({ title: 'Default Toast', description: 'This is a default toast notification' })">Default
              Toast</Button>

            <Button variant="secondary"
              @click="toast.success({ title: 'Success!', description: 'Your action was completed successfully' })">Success
              Toast</Button>

            <Button variant="destructive"
              @click="toast.error({ title: 'Error!', description: 'Something went wrong with your request' })">Error
              Toast</Button>

            <Button variant="outline"
              @click="toast.info({ title: 'Info', description: 'Here is some useful information' })">Info Toast</Button>

            <Button variant="ghost"
              @click="toast({ title: 'With Action', description: 'This toast has an action button', action: { label: 'Undo', onClick: onUndo } })">Toast
              with Action</Button>
          </div>
        </CardContent>
      </Card>
    </div>
  </div>
</template>

// examples/shadcn-ui/src/app/page.tsx
'use client'

import * as PopoverPrimitive from '@radix-ui/react-popover'
import { toast } from 'sonner'
import { useAsk } from 'use-ask'

import { useAlertDialogConfirm } from '@/components/alert-dialog-confirm-provider'
import {
  DeleteRepositoryForm,
  DeleteRepositoryFormFields,
  DeleteRepositoryFormSubmitButton,
  type DeleteRepositoryFormData,
} from '@/components/delete-repository-form'
import { ModeToggle } from '@/components/mode-toggle'
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Popover, PopoverContent } from '@/components/ui/popover'
import {
  UpdateRepositoryForm,
  UpdateRepositoryFormFields,
  type UpdateRepositoryFormData,
} from '@/components/update-repository-form'

const Home = () => {
  const [{ safeAsk: safeAskDeleteRepository }, askDeleteRepository] =
    useAsk<DeleteRepositoryFormData>()
  const [{ safeAsk: safeAskRenameRepository }, askRenameRepository] = useAsk()
  const { confirm } = useAlertDialogConfirm()
  const [{ ask }, { asking, cancel, ok }] = useAsk<string, Error>()

  const handleDeleteRepository = async () => {
    const answer = await safeAskDeleteRepository()
    if (!answer.ok) {
      return
    }

    toast.success(`Successfully deleted repository ${answer.data.repository}.`)
  }

  const handleRenameRepository = async (data: UpdateRepositoryFormData) => {
    const answer = await safeAskRenameRepository()
    if (!answer.ok) {
      return
    }

    toast.success(`Successfully renamed repository ${data.repository}.`)
  }

  return (
    <div className="flex min-h-dvh flex-col">
      <header className="flex justify-end p-6">
        <ModeToggle />
      </header>
      <main className="grid flex-1 place-items-center px-6">
        <Popover open={asking} onOpenChange={(open) => !open && cancel()}>
          <PopoverPrimitive.Anchor asChild>
            <Button
              onClick={() =>
                ask()
                  .then((message) => alert(`Confirmed with message "${message}"`))
                  .catch((error) => alert(`Cancelled with message "${error.message}"`))
              }
            >
              Rename
            </Button>
          </PopoverPrimitive.Anchor>
          <PopoverContent side="right">
            <div className="flex gap-2">
              <Button
                variant="outline"
                className="w-full"
                onClick={() => cancel(new Error('No good!'))}
              >
                Cancel
              </Button>
              <Button className="w-full" onClick={() => ok('All good!')}>
                Continue
              </Button>
            </div>
          </PopoverContent>
        </Popover>
        <AlertDialog
          open={askDeleteRepository.asking}
          onOpenChange={(open) => !open && askDeleteRepository.cancel()}
        >
          <AlertDialogContent asChild>
            <DeleteRepositoryForm onSubmit={askDeleteRepository.ok}>
              <AlertDialogHeader>
                <AlertDialogTitle>Delete junwen-k/use-ask</AlertDialogTitle>
                <AlertDialogDescription>
                  This action cannot be undone. This will permanently delete your repository and
                  remove your data from our servers.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <DeleteRepositoryFormFields />
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <DeleteRepositoryFormSubmitButton />
              </AlertDialogFooter>
            </DeleteRepositoryForm>
          </AlertDialogContent>
        </AlertDialog>

        <div className="grid w-full max-w-screen-md gap-8">
          <div className="grid gap-2">
            <h2 className="text-2xl">General</h2>
            <Popover
              open={askRenameRepository.asking}
              onOpenChange={(open) => !open && askRenameRepository.cancel()}
            >
              <UpdateRepositoryForm
                onSubmit={handleRenameRepository}
                className="w-full max-w-md space-y-4"
              >
                <UpdateRepositoryFormFields />
                <PopoverPrimitive.Anchor asChild>
                  <Button type="submit">Rename</Button>
                </PopoverPrimitive.Anchor>
                <PopoverContent side="right">
                  <div className="grid gap-4">
                    <div className="grid gap-2">
                      <h4 className="font-medium leading-none">Rename repository</h4>
                      <p className="text-muted-foreground text-sm">
                        Renaming repository might have unwanted consequences, please proceed with
                        caution.
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        className="w-full"
                        onClick={askRenameRepository.cancel}
                      >
                        Cancel
                      </Button>
                      <Button className="w-full" onClick={askRenameRepository.ok}>
                        Rename
                      </Button>
                    </div>
                  </div>
                </PopoverContent>
              </UpdateRepositoryForm>
            </Popover>
          </div>
          <div className="grid gap-2">
            <h2 className="text-2xl">Danger Zone</h2>
            <ul className="border-destructive/50 bg-card text-card-foreground divide-y rounded-lg border">
              <li className="flex flex-wrap items-center justify-between gap-4 p-4">
                <div className="text-sm">
                  <h6 className="font-semibold">Archive this repository</h6>
                  <p className="text-muted-foreground">
                    Mark this repository as archived and read-only.
                  </p>
                </div>
                <Button
                  variant="destructive"
                  onClick={() =>
                    confirm({
                      title: 'Archive repository',
                      description:
                        'This repository will become read-only. You will still be able to fork the repository and unarchive it at any time.',
                      actionText: 'Archive',
                      ActionProps: {
                        variant: 'destructive',
                      },
                    })
                      .then(() => toast.success('Successfully archived repository.'))
                      .catch(() => {})
                  }
                >
                  Archive this repository
                </Button>
              </li>
              <li className="flex flex-wrap items-center justify-between gap-4 p-4">
                <div className="text-sm">
                  <h6 className="font-semibold">Delete this repository</h6>
                  <p className="text-muted-foreground">
                    Once you delete a repository, there is no going back. Please be certain.
                  </p>
                </div>
                <Button variant="destructive" onClick={handleDeleteRepository}>
                  Delete this repository
                </Button>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
