// apps/vue-demo/app/components/confirmer.vue
<script setup lang="ts">
import { useSingletonCallStore } from '@ui-call/vue';

const call = useSingletonCallStore(confirmStore);
</script>

<script lang="ts">
import { createSingletonCallStore } from '@ui-call/vue';

const confirmStore = createSingletonCallStore<{
  title: string;
  message: string;
}>({
  unmountingDelay: 200,
});

export const confirm = confirmStore.call.bind(confirmStore);
</script>

<template>
  <ConfirmationDialog v-if="call" :open="Boolean(call)" :closing="!call.pending" :title="call.payload.title"
    @confirm="call.resolve(true)" @cancel="call.resolve(false)">
    {{ call.payload.message }}
  </ConfirmationDialog>
</template>

// apps/preact-demo/src/components/confirmer.tsx
import { createSingletonCallStore, useSingletonCallStore } from '@ui-call/preact';

const confirmStore = createSingletonCallStore<string>();

export const confirm = confirmStore.call.bind(confirmStore);

export function Confirmer() {
  const call = useSingletonCallStore(confirmStore);
  if (!call) {
    return null;
  }

  return (
    <dialog
      open={call.pending}
      onCancel={() => call.resolve(false)}
      onClose={() => call.resolve(false)}
    >
      <p>{call.payload}</p>
      <button onClick={() => call.resolve(true)}>OK</button>
      <button onClick={() => call.resolve(false)}>Cancel</button>
    </dialog>
  );
}
